version: '3'

services:
  service_lint_test:
    build:
        context: .
        dockerfile: Dockerfile.ci
    ports:
      - "8000:8000"
    env_file:
      - ./.env.dev
    networks:
        - custom
    depends_on:
        - db
  db:
    image: postgres:15
    environment:
      - POSTGRES_USER=hasker
      - POSTGRES_PASSWORD=hasker
      - POSTGRES_DB=hasker_dev
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    ports:
        - "5432:5432"
    networks:
        - custom

volumes:
    postgres_data:
networks:
  custom:
    driver: bridge